### ISSUE TITLE
User guide for invocation within python script 

### ISSUE THREAD

**Issue by RSwarnkar** [fgiuba/ipconflict#3]
How to call `ipconflict` that takes filepath argument within Python script.

**Comment by fgiuba** [comment]
`ipconflict` is not meant to be used as a Python library, it is just a CLI tool.
Of course, you can still use it in your Python script by invoking an external process with the `subprocess` module.
```
import subprocess
subprocess.run('ipconflict -f /my/subnets', shell=True)
```
