### ISSUE TITLE
Slow performance for large input set

### ISSUE THREAD

**Issue by RSwarnkar** [fgiuba/ipconflict#4]
I have enterprise IP subnet entry for about 13k subnets in a text file.
The command takes too long to generate output list. I guess the complexity is n-squared. Is there more efficient way to get  output?

**Comment by RSwarnkar** [comment]
May be the performance can be improved by using radix tree (py-radix) to store the data.

**Comment by fgiuba** [comment]
I have added two improvements to the conflict lookup algorithm:
1. As you suggested, we now use `py-radix` for storing the checked subnets while iterating.
2. We check for real conflicts only when a conflict is found between a subnet and the previously checked ones (stored in the py-radix tree).

In this way the algorithm has still n-squared complexity but it is strongly optimized for a no-conflict scenario. If you have few conflicts in your file, you'll see a significant performance improvement.
