### ISSUE TITLE
exit code

### ISSUE THREAD

**Issue by ciroiriarte** [fgiuba/ipconflict#6]
Would it be possible to add exit codes to be able to evaluate the outcome using scripts?. Right now, conflict or not, the exit code is always 0

**nas02:/tmp/ip-test #** ipconflict 10.0.0.0/22 10.0.1.0/24
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 5275.85subnet/s]
conflict found: 10.0.0.0/22 <-> 10.0.1.0/24

**nas02:/tmp/ip-test #** echo $?
0
**nas02:/tmp/ip-test #** ipconflict 10.0.0.0/22 11.0.1.0/24
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 5457.78subnet/s]
no conflict found
**nas02:/tmp/ip-test #** echo $?
0

**Comment by fgiuba** [comment]
Yes, I think this is a good idea.

So far we used exit code 0 for any valid result (conflict/no-conflict) and exit code 1 for invalid parameters. I would prefer to do as follow:

- 0  - No conflict.
- 1  - One or more conflicts found.
- 2 -  Invalid parameters.

**Comment by ciroiriarte** [comment]
There are some conventions for comparison tools, maybe it's a little counterintuitive given we're "looking for conflicts"

> There are conventions for what sorts of status values certain programs should return. The most common convention is simply 0 for success and 1 for failure. **Programs that perform comparison use a different convention: they use status 1 to indicate a mismatch, and status 2 to indicate an inability to compare**. Your program should follow an existing convention if an existing convention makes sense for it.

If I interpret that correctly, it should be the other way around -_-'

Eitherway, if it's documented I think it will effective.

Ref: https://www.gnu.org/software/libc/manual/html_node/Exit-Status.html

**Comment by fgiuba** [comment]
I agree, let's follow the existing conventions. So, exit status will be:
- 0 - One or more conflicts found.
- 1 - No conflict found.
- 2 - Aborted or invalid input.
